app/src/main/AndroidManifest.xml
app/src/main/java/com/example/woowagithubrepositoryapp/App.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileViewModel.kt
app/src/main/res/layout/activity_profile.xml
app/src/main/res/values/strings.xml

---
user 정보에서 starred  값 구하기
tag 정보 구하기 (디자인 예시에서 Android Developer 부분)
---
리소스 네이밍 협의 필요
```
<string name="main_title">What\'s In My GitHub</string>
<string name="appbar_title">What\'s In My GitHub</string>
```

#7 Profile 화면 작업

---

app/src/main/java/com/example/woowagithubrepositoryapp/model/Issue.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/Repo.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/RepoOwner.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/RepoResponse.kt
app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginActivity.kt
app/src/main/res/layout/activity_profile.xml

- Issue : 사용자의 issue 정보
- Repo : Issue나 notification의 repository 정보나 검색한 repository 정보
- RepoOwner : repository의 Owner 정보 (login, avatar_url)
- RepoResponse : 실제로 response의 body로 전달받을 데이터 타입
---
- activity_profile.xml : 오타 수정

#9 네트워크 issue, repository 검색

---

app/build.gradle
app/src/main/java/com/example/woowagithubrepositoryapp/utils/BindingAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/utils/TimeUtil.kt
app/src/main/res/layout/item_notification.xml

#8 유틸 - 바인딩 어댑터 추가, TimeUtil 추가

---

app/src/main/java/com/example/woowagithubrepositoryapp/model/Issue.kt
app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/IssueAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/SpinnerAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueViewModel.kt
app/src/main/res/drawable/spinner_background.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_issue.xml
app/src/main/res/layout/item_issue.xml
app/src/main/res/layout/item_spinner.xml
app/src/main/res/values/strings.xml

---
- custom spinner - dropdown arrow 방향 전환

#4 issue 화면 구현

---

app/src/main/java/com/example/woowagithubrepositoryapp/model/Notification.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/SuccessResponse.kt
app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/NotificationAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/utils/NotificationItemHelper.kt
app/src/main/res/layout/item_notification.xml

#5 알림 Swipe 작업

---

app/src/main/java/com/example/woowagithubrepositoryapp/model/Notification.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/NotificationSubjectURLResponse.kt
app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/NotificationAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/utils/BindingAdapter.kt
app/src/main/res/layout/item_notification.xml

스레드와 retrofit을 이용해서 어댑터의 각 아이템에 필요한 데이터를 Get 방식으로 가져와서 UI상에 나타나게 했습니다.
아무래도 추가적인 통신 작업이다보니 각 목록이 나타나고 난 후에 스레드 작업이 완료된 후 해당 데이터들이 나타나서 늦게 확인될 수 있습니다.

#5 알림 어댑터 내 네트워크 작업

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/woowagithubrepositoryapp/model/Repo.kt
app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/RepositoryAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
app/src/main/res/drawable/ic_variant10.xml
app/src/main/res/drawable/shape_circle.xml
app/src/main/res/layout/activity_search.xml
app/src/main/res/layout/item_repo.xml

---
- SearchActivity : 기능 구현을 위해 임시로  작성, 수정 필요

#6 Search 화면 구현

---

app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/IssueAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt

#28 refactor - 코드 수정

---

app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/network/TokenService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/repository/TokenRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/utils/ViewModelFactory.kt
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_profile.xml

ViewModelFactory를 이용해 ViewModel 생성 시 각 viewModel 에서 사용할 repository를 넣어주도록 했습니다.

#28 refactor - ViewModelFactory 적용

---

app/src/main/java/com/example/woowagithubrepositoryapp/model/NotificationInfo.kt
app/src/main/java/com/example/woowagithubrepositoryapp/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/NotificationAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/utils/NotificationItemHelper.kt
app/src/main/res/layout/item_notification.xml

#38 Notification 코드 개선

---

app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/NotificationAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt

알림 관련 불필요한 개행과 로그 태그가 계속 걸려서 수정하였습니다.

#28 알림 관련 불필요한 개행 삭제, 로그 태그 수정

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
app/src/main/res/layout/activity_search.xml

#6 Search - 1초간 텍스트 변화 없을 시 자동 검색

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationViewModel.kt

이후 작업인 상태 유지와 백그라운드에서 네트워킹을 위한 뷰모델 통합 작업

#47 알림 뷰모델, 이슈 뷰모델을 메인 뷰모델로 통합

---

app/src/main/res/layout/fragment_issue.xml

filter bar layout 초기 background 수정

#4 issue - filter bar 초기 background 수정

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/adapter/SpinnerAdapter.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
app/src/main/res/drawable/ic_spinner_drop_down.xml
app/src/main/res/drawable/spinner_background.xml
app/src/main/res/drawable/spinner_selected_background.xml
app/src/main/res/layout/fragment_issue.xml
app/src/main/res/layout/item_spinner_default.xml

#28 refactor - spinner drawable focusing에 따라 전환 방법 변경

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_profile.xml

- MainActivity : 현재 선택 fragment 유지
- IssueFragment : 현재 선택 filter 유지
- ProfileActivity : scroll 추가로 기기 회전시에도 짤림 없이 모두 확인 가능

#51 기기 회전 대응

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt

남은 알림이 없는데도 계속 get요청을 보내서 수정하였습니다.

#42 알림 - 이전 알림 목록의 사이즈를 통해 요청을 할지 말지 결정하게 코드 수정

---

app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt

뷰모델에서는 요청 응답 과정을 알 필요가 없기 때문에 Result를 이용하여 데이터와 에러 여부만 받을 수 있도록 Result 적용

refactor Notification 리포지토리 - 뷰모델 Result 적용

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
app/src/main/res/layout/activity_search.xml

#28 refactor - search bar backgrond 전환 로직 변경

---

app/src/main/java/com/example/woowagithubrepositoryapp/model/AccessTokenResponse.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/Repo.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/User.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
app/src/main/res/layout/activity_profile.xml

불필요한 개행, 데이터 값, import 등을 제거했습니다.

#28 refactor - 불필요 개행, 코드라인 제거

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileViewModel.kt

Profile 화면 실행시 user data를 다시 불러와 최신화를 하도록 했습니다.

#7 Profile - Profile 화면 실행시 user Data 최신화 적용

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt

#70 notification reselect 시 중복 호출 문제

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/res/layout/activity_profile.xml

#77 리팩토링중 발생한 오류 수정

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/common/TabSelectState.kt
app/src/main/java/com/example/woowagithubrepositoryapp/utils/Constants.kt

기존 replace를 통해 프래그먼트를 전환하니 프래그먼트가 새로 만들어지는 것으로 판단되어 show & hide로 변경하였습니다!

refactor 프래그먼트 전환 로직 변경

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt

검색을 하는 상황을 분류해 화면 회전의 경우 새로 검색을 하는 것이 아닌 이미 검색한 데이터를 그대로 출력만 할 수 있도록 했습니다.
그리고 RecyclerView의 스크롤 위치를 저장해 스크롤 위치도 유지할 수 있도록 했습니다.

#51 rotate - search 데이터 유지 및 스크롤 위치 유지

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt

feat 알림 - 기기 회전 시 현재 알림 목록 크기를 이용하여 호출을 할지 말지 결정

---

app/src/main/java/com/example/woowagithubrepositoryapp/repository/GithubRepository.kt

불필요한 자료 구조를 제거하고 zip 함수를 이용해서 두 데이터를 가공하도록 개선하였습니다.

#86 refactor - awaitAll, zip 사용하여 불필요한 리스트, 맵 삭제 및 코드 개선

---

app/src/main/res/layout/item_notification.xml

요구 사항의 UI와 다르게 표기가 되어있어서 수정하였습니다.

bug 요구사항에 맞게 fullName으로 수정

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt

#28 refactor - DataBinding -> ViewBinding 으로 변경

---

app/src/main/java/com/example/woowagithubrepositoryapp/data/network/GithubClient.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/network/GithubService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/network/TokenInterceptor.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/network/TokenService.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/GithubRepositoryImpl.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/TokenRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/TokenRepositoryImpl.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/auth/LoginViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/common/ViewModelFactory.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/common/states.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/issue/IssueFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationItemHelper.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/profile/ProfileViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchActivity.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/search/SearchViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/utils/Constants.kt
app/src/main/res/layout/activity_login.xml

#65 refactor - 패키지 변경 및 코드 개선

---

app/src/main/java/com/example/woowagithubrepositoryapp/data/network/GithubClient.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/TokenRepositoryImpl.kt
app/src/main/java/com/example/woowagithubrepositoryapp/utils/TimeUtil.kt

- 불필요 코드라인 제거
- 함수 이름 변경 (refresh 라는 표현이 맞지 않는 것 같아 수정)

#28 refactor - 코드 개선

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainActivity.kt
app/src/main/res/values/strings.xml

#28 refactor - 중복 리소스 통일

---

app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt

issueFragment를 참고하여 binding이나 observer처리를 수정하였습니다.

#28 Refactor - 알림 코드 개선

---

app/src/main/java/com/example/woowagithubrepositoryapp/data/datasource/GithubDataSource.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/datasource/GithubRemoteDataSourceImpl.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/GithubRepository.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/GithubRepositoryImpl.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/NotificationInfo.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/MainViewModel.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationFragment.kt
app/src/main/java/com/example/woowagithubrepositoryapp/ui/notification/NotificationItemHelper.kt

#107 Refactor - DataSource DI 관련 수정

---

app/src/main/java/com/example/woowagithubrepositoryapp/data/datasource/GithubDataSource.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/datasource/GithubRemoteDataSourceImpl.kt
app/src/main/java/com/example/woowagithubrepositoryapp/data/repository/GithubRepositoryImpl.kt
app/src/main/java/com/example/woowagithubrepositoryapp/model/NotificationInfo.kt

Repository에서 datasource 의존성 추가하는 방식 수정 필요

#65 Refactor DataSource 추가
